name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: AliceKh/rick-and-morty
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster
        run: kubectl get pods -A
      - name: enable Ingress
        run: minikube addons enable ingress
      - name: Build image
        run: |
          minikube image build -t alicekh/rickandmorty:0.1.0 api/.
      - name: Deploy to minikube
        run: |
          kubectl apply -f api/yamls
          kubectl wait --for=condition=ready pod -l app=rickandmorty
      - name: Test service URLs
        run: |
          minikube service list
          minikube service rickandmorty --url
          echo "------------------opening the service------------------"
          curl -L --resolve "rickandmorty.elementor:80:$( minikube ip )" -i http://rickandmorty.elementor
          

